Polymorphism
KruminsP/PK pull request #9
Opened 2022-08-23 15:29 UTC by KruminsP

Poly done

2022-08-23 19:44 UTC, ausmoons requested changes

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRace/ZAZ.cs
> +        public void StartEngine()
Starp metodēm tukša rinda

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +        public string firstName { get; }
Public vai private?

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +            this.firstName = firstName;
bez this.

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public string animalType { get; }
private

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +            this.animalWeight = animalWeight;
bez this.

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Persons/Person.cs
> +        public string address { get; }
private

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Persons/Person.cs
> +            this.lastName = lastName;
bez this.

2022-08-23 19:44 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +        public bool AddProduct(string name, Money price, int count)
bool AddProduct?

2022-08-25 09:14 UTC, KruminsP commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +        public string firstName { get; }
firstName ir jābūt private vai protected, ja viņam nav public set?

2022-08-25 09:16 UTC, KruminsP commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +            this.firstName = firstName;
Kā te no this var izvairīties, ja parametram un argumentam ir vienāds nosaukums? Vai speciāli vajadzētu izvairīties no vienādiem, lai nejūk?

2022-08-25 09:38 UTC, KruminsP commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +        public bool AddProduct(string name, Money price, int count)
Tā interfeisā bija dots, un uzdevuma nosacījums bija nemainīt to.
Uztaisīju šādi -j  true tad produkts pievienojas, ja false, tad met erroru.

if (myMachine.AddProduct(name, new Money(euro, cents), amount)) 
            {
                Console.WriteLine();
            }
            else
            {
                Console.WriteLine("All slots taken");
                Console.ReadKey();
            }

2022-08-26 07:35 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +            this.firstName = firstName;
_address un tad nejuks

2022-08-26 07:37 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public string animalType { get; }
Es labāk taisītu jaunus ar private, jo tev šeit tik un tā ir tikai get

2022-08-28 08:02 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +        public string firstName { get; }
private un bez get

2022-08-28 08:03 UTC, ausmoons requested changes

2022-08-28 08:03 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +
Jānoņem get un this

2022-08-30 09:32 UTC, ausmoons requested changes

2022-08-30 09:32 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +            this.firstName = firstName;
Šeit nav labots. Pārskati visus failus

2022-08-31 16:51 UTC, ausmoons approved these changes

2022-08-31 16:57 UTC, merged